apiVersion: apps/v1
kind: Deployment
metadata:
  name: winston-log-deployment
  namespace: sandbox
  labels:
    app: winston-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winston-log
  template:
    metadata:
      labels:
        app: winston-log
    spec:
      containers:
      - name: winston-log
        image: arturcorreiajr/node-winston:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: webinterface
---
apiVersion: v1
kind: Service
metadata:
  name: winston-log
  namespace: sandbox
  labels:
    service: winston-log
spec:
  type: NodePort
  ports:
  - port: 4000
    name: webinterface
  selector:
    app: winston-log